#These are properties for building hadoop mostly.  They point to a few tools that are not very standard, and need to be in a special place
forrest.home=/home/evans/src/hadoop/dependencies/libexec/forrest/
java5.home=/home/evans/src/hadoop/dependencies/libexec/jdk1.5.0/
findbugs.home=/home/evans/bin/findbugs-1.3.9/
